### ISSUE TITLE
Parent products on shopping list

### ISSUE THREAD

**Issue by Festeazy** [PantryParty/pantry_party#101]
Let's say I have a parent product in a shopping list for "paper towel"
I think if I purchase any of its child-products, it should remove the parent products from the shopping list.

Actually any item that is purchased should be removed from the shopping list if it's on there

**Comment by arjes** [comment]
Are you talking about the products below minimum stock (https://pantryparty.app/docs/basic_usage/current-stock.html)?

PantryParty hasn't integrated with the Grocy shopping list yet.

If you are saying that Grocy's normal purchase flow in the web ui will take items off the shopping list, then you are correct I did not know that was a feature and did not implement that.
