### ISSUE TITLE
App does not accept local IP and port for Grocy URL

### ISSUE THREAD

**Issue by MoralCode** [PantryParty/pantry_party#104]
it seems as though I am unable to set up PantryParty on iOS with an instance of grocy that's running just on my local network with no external access or domain name (and custom port number). after pressing the "return" button the app seems to not do anything, which I suspect is because the formatting of the URL doesn't match the pattern suggested.

Is it possible to just use PantryParty for a local-network-only instance of grocy without a domain name?

![IMG_6474](https://user-images.githubusercontent.com/17362949/101296334-af17c900-37d7-11eb-9b4a-dae89e531f4b.PNG)

iOS Version 13.3.1
Pantry Party Version 1.1.5

**Comment by arjes** [comment]
Just stick an `http` on the front and you should be fine. `http://192.168.0.30:9283/api`. Let me know if you have any trouble!

**Comment by MoralCode** [comment]
awesome that fixed it, thanks!

Would a pull request to clarify the language of the warning be helpful?

**Comment by bmalinconico** [comment]
Absolutely. I recently moved and my Grocy setup is down, so I'm not actively using the app right now.

**Comment by coaxial** [comment]
It doesn't work with this string, which is what I get using HASSOS: http://homeassistant.lan:8123/api/hassio_ingress/RGpyaaaa4Ge7KSiM4AVfGnTY4xhJ1zHZWvZupcsx7Xo/api/system/info

**Comment by ArchdukeTim** [comment]
@MoralCode you should close this issue now that #105 was merged
