### ISSUE TITLE
App Crashes once opening camera

### ISSUE THREAD

**Issue by userbradley** [PantryParty/pantry_party#114]
Hey!

had a look and saw this similar issue here: https://github.com/PantryParty/pantry_party/issues/93

I open the app, click the QR code to scan the API and it crashes immediatly.

IOS 14.4.1
Iphone 12

Let me know if you require additional info!

**Comment by arjes** [comment]
Sorry about that. Version 1.2.2 is pending Apple's approval and should
fix the issue.

**Comment by arjes** [comment]
Hey 1.2.2 was just approved and should be available for download. Can you give the camera a try?

**Comment by userbradley** [comment]
Hey!

This works! Thanks for the quick turn around!
