### ISSUE TITLE
crash on intialising QR scan for login

### ISSUE THREAD

**Issue by catatonicChimp** [PantryParty/pantry_party#120]
Just installed Pantry Party yesterday, initial "Welcome to Pantry Party!" loads fine, but after clicking ready to go and then trying to login via the QR code button it just crashes straight to home screen

**Comment by catatonicChimp** [comment]
IOS 14.5.1
Iphone12 Pro

**Comment by arjes** [comment]
Sorry about that. That was an issue a couple of versions ago, I just want
to make sure you are using the latest and greatest?

**Comment by arjes** [comment]
I was able to reproduce it and I'll let you know when a fix is ready.

**Comment by arjes** [comment]
Bug fix is on the way to the ios app store. It can take apple up to 24hrs to approve a new release, so let me know when you see it and if it fixes it for you.

**Comment by arjes** [comment]
Thanks for the confirmation. A new version with the fix is in Apple's queue
for approval. Look for a new version sometime today. I'll ping this thread
when I got the approval

**Comment by arjes** [comment]
The updated app should now be available.

**Comment by rolfberkenbosch** [comment]
It's indeed fixed, thanks!

**Comment by catatonicChimp** [comment]
awesome yip finally figured out how to get ios14.5 to update an app manually, can confirm its working here
