### ISSUE TITLE
Barcode of 8 digits is not recognized by the app

### ISSUE THREAD

**Issue by rolfberkenbosch** [PantryParty/pantry_party#121]
Hi I can scan barcodes of 13 digits, but products of 8 digits is not recognized by the app. I don't hear a beep sound. For example: 23006027

**Comment by arjes** [comment]
Can you take a picture of the barcode and upload it? Unfortunately not all
barcode formats are recognized by the camera, but I also didn't enable all
of them. If you can send a pic of the one you are having trouble with i can
check the app against that one specifically.

There are what is supported, I assume you are looking at an EAN_8

* iOS and Android
CODE_39
CODE_93
CODE_128
DATA_MATRIX
EAN_8
EAN_13
ITF (also known as ITF14)
PDF_417 (on Android only when passed in explicity via formats)
QR_CODE
UPC_A
UPC_E

* Android only
CODABAR
MAXICODE
RSS_14

* iOS only
AZTEC
CODE_39_MOD_43
INTERLEAVED_2_OF_5
