### ISSUE TITLE
Create Product: Save button on Android App

### ISSUE THREAD

**Issue by kriddles** [PantryParty/pantry_party#41]
Clicking the Save button on the Create Product screen is not performing any action.

**Comment by arjes** [comment]
Doh I'm able to reproduce and will get that fixed tonight.

**Comment by arjes** [comment]
This appears to be related to selecting a location the form will save if there is no location selected. I really hate this form builder I used, I may need to rip it out.

**Comment by arjes** [comment]
I'm not going to be able to finish this one tonight other reported issues ended up higher priority.

**Comment by kriddles** [comment]
No worries, thanks for the update
