### ISSUE TITLE
Bug: Purchasing an item that is a pack only adds 1 piece

### ISSUE THREAD

**Issue by tisboyo** [PantryParty/pantry_party#42]
When using the Purchase option in Pantry Party it only adds one Piece instead of Piece * Factor.

Steps to reproduce:
Add Item to Grocy with Quantity Unit Purchase set to Pack, Quantity Unit Stock  set to Piece and  Factor purchase to stock quantity unit  set to more than 2 (or more).

In Pantry Party, Scan-Purchase, scan the item and let it upload. 

Expect the new piece count to equal Old + (Piece * Factor)  1 + ( 1 * 2) = 3 but getting only 2.

On Android

**Comment by arjes** [comment]
Thanks for the report, I (incorrectly) assumed this was done on the backend. I'm working on an update to be released tonight and I'll have that fixed for a release tomorrow.
