### ISSUE TITLE
Android Can't Handle Capitalization of URL in initial setup of Grocy URL

### ISSUE THREAD

**Issue by focalfury** [PantryParty/pantry_party#48]
When typing in the URL my Android phone capitalized the H in Https://URL/api and I was unable to proceed with setup.  

After manually forcing it to be **https** I was able to continue

Changing it from /api to /apI produced the same result.  So it looks like any capitalization will produce the error

**Comment by arjes** [comment]
Thanks. Fixed by https://github.com/PantryParty/pantry_party/pull/49 I should be releasing it tonight (takes up to a day to get approval from Apple)
