### ISSUE TITLE
Unable to navigate around android app after pressing back from settings menu

### ISSUE THREAD

**Issue by frazzyfin** [PantryParty/pantry_party#52]
Pantry Party Android App v1.0.6

Step to reproduce:

1. Open Pantry Party
2. Open hamburger menu and click on Settings.
3. Press back button to get back to previous screen.
4. Try to navigate elsewhere on the app through the hamburger menu. You will stay on the current screen.

**Comment by arjes** [comment]
Thanks for the report.

Were you on the purchase page when you navigated to the settings page?

There isn't supposed to be a back button on the main settings list page, I wonder if something went wrong earlier in the processes.

**Comment by frazzyfin** [comment]
Actually it happens if I go to settings from any page.

And just to clarify, by back button, i mean the android back button which is built into the OS and available everywhere.

**Comment by arjes** [comment]
Ah, alright then. On my phone the back button works and then nothing works at all after that!

I'll take a look and see what I can find.

**Comment by arjes** [comment]
Thanks for the report, I'll try and get this fix out tonight to both app stores.
