### ISSUE TITLE
ISSUES: Never expire incorrect

### ISSUE THREAD

**Issue by Belafestim** [PantryParty/pantry_party#62]
When you select never expire, it ends up setting the value as negative one, so it sets expiration as yesterday.

Everything I set today to never expire is showing as expiring yesterday

**Comment by arjes** [comment]
Did you close this on purpose? -1 is the grocy config for never expiring but I PantryParty may be handling it incorrectly.

**Comment by arjes** [comment]
Fixed in https://github.com/PantryParty/pantry_party/pull/65

Sorry for any of your stock I screwed up. Release should be available tomorrow
