### ISSUE TITLE
Feature Request: Back in product creation

### ISSUE THREAD

**Issue by kses** [PantryParty/pantry_party#69]
I was creating many products while shopping today. If I am not missing it, a back button to previous step is not available when creating a new product. For when you realized you were a bit quick on the next button. Would be useful.

(QU auto selecting the same as PU would be great when creating a new product but that is even less minor than the back button)

**Comment by arjes** [comment]
I can add a more explicit option, but swipe right should let you move back
a step.

**Comment by kses** [comment]
That works great! Just to stupid to realize that was possible. A more explicit might be nice to have but not a necessity.
