### ISSUE TITLE
'Open' not working as expected/Grocy Home Assistant

### ISSUE THREAD

**Issue by CerebralBypass** [PantryParty/pantry_party#76]
The 'Open' function doesn't mark the product as opened in Grocy but actually Consumes it.
Inititally, 'Consume' didn't work (scanned items stuck waiting forever) but after navigating to the Consume page in Grocy it somehow got resolved.

I'm using the latest Pantry Party app for Android (1.0.10), Grocy Version 2.6.0, Home Assistant HassOS 3.13

**Comment by arjes** [comment]
Moved this to the code repo.

Yep sorry about this I noticed last night when I was working on another feature. It will be fixed in the next release.

**Comment by arjes** [comment]
This is out in the most recent release, let me know if you still have issues!
