### ISSUE TITLE
Current Stock - Android crash

### ISSUE THREAD

**Issue by grov3r** [PantryParty/pantry_party#82]
When clicking an item in the new 1.1.0 Android app, the app crashes.  Sent in a report via Google feedback with the Stack Trace.  Appears to be an issue with Theme/Material Design.

**Comment by arjes** [comment]
Thanks for the report, I am able to reproduce locally and i'll get a fix out or yank that shortly.

**Comment by arjes** [comment]
The fix for this will go out tonight, look for an update soon

**Comment by grov3r** [comment]
Thanks for the quick fix, and the great app to integrate with Grocy
